### PR TITLE
Windows paths are forwarded using / instead of \ to EditorConfig.

### LINKED ISSUE #6: File is parsed, but no settings applied.
I'm pretty sure to use your plugin as described and can see on Windows that `.editorconfig` is parsed by some Java process. Additionally I see different behaviour of Java in case `root = true` is present in the file vs. when it is not: If it's present only one `.editorconfig` is parsed, if it's not the directory tree is searched upwords for additional files until `C:\.editorconfig`, which is not found in the end.

Running the task `cleanEclipse` as well deletes all your managed files, while the task `eclipse` generates all of those containing the line with the version number only. I've already compared behaviour of both tasks with/without your plugin and there's a difference as well, because some of the `prefs`-files are only created by your plugin, not the one name `eclipse` already.

But whatever I put into `.editorconfig`, besides `root = true` nothing seems to be recognized and I already only copied the examples from you. I don't even get any errors logged, it simply seems that all statements are completely ignored, not with wrong values.

Any idea what could be the problem? Are there any logs available for EditorConfig?

Thanks!

### PR DESCRIPTION
**Pull request by ams-tschoening**
This fixes #6 and I additionally improved logging a bit to find such errors easier in future.

### CODE REVIEW

**Comment by ams-tschoening** [comment]
While it doesn't make much sense to me, that's what the maintainer of `editorconfig-core-java` says:

> If so, the plugin should normalize the path before it passes the path to editorconfig-core-java[...]

https://github.com/editorconfig/editorconfig-core-java/issues/16#issuecomment-433518131

So merging this PR seems a lot easier than to implement #7 for now and not even that hacky regarding the former quote.

**Review by stempler — APPROVED** [review]

**Comment by stempler** [comment]
Thanks a lot! Included in 1.1.1 release.

**Comment by ams-tschoening** [comment]
Thanks, any idea when the release will be available publicly by Maven and as plugin in Gradle? Is it more about hours or days or didn't you publish there yet? I `would just like to know when to switch my `build.gradle` to not use my local build anymore.

**Comment by stempler** [comment]
I triggered both yesterday, so if they are not available yet it should be soon. On the Gradle plugins site the version already showed yesterday (though resolving did not work yet).

**Comment by ams-tschoening** [comment]
There might be an error with your publishing, could you have a look at the following please? It might need to be approved again. Thanks!

https://discuss.gradle.org/t/a-new-version-of-a-plugin-is-identified-as-new-plugin-instead-of-an-update/28331/7

https://discuss.gradle.org/t/is-the-plugin-https-plugins-gradle-org-m2-org-standardout-gradle-eclipseconfig-1-1-1-broken/29338

**Pull request merged**
